version: "3"
services:
  reverseproxy:
      image: zmarozas/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: zmarozas/udagram-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://addd5f7c5084146c8a26baac2d6ea06b-1815322002.us-east-1.elb.amazonaws.com:8100"
  backend-feed:
    image: zmarozas/udagram-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://addd5f7c5084146c8a26baac2d6ea06b-1815322002.us-east-1.elb.amazonaws.com:8100"
  frontend:
    image: zmarozas/udagram-frontend
    ports:
      - "8100:80"
