version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: zmarozas/reverseproxy
  backend_user:
    build:
      context: ../../udagram-user
    image: zmarozas/udagram-user
  backend_feed:
    build:
      context: ../../udagram-feed
    image: zmarozas/udagram-feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: zmarozas/udagram-frontend
